baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vicente Guerrero"
theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""


[params]
    author = "Vicente Guerrero"
    description = "Vicente Guerrero's personal website"
    keywords = "blog,developer,personal,software"
    info = "Freelance Software Developer"
    avatarurl = "images/me3.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "Let's do stuff together."

    dateformat = "Oktober 10, 2020"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# # If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"

# # If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
#     domain = "example.com"
#     # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#     serverURL = "analytics.example.com"

# # If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
#     code = "code"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/viclule/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fa fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/chente_chente1/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/vicente-guerrero/"
# [[params.social]]
#     name = "Medium"
#     icon = "fa fa-medium"
#     weight = 5
#     url = "https://medium.com/@johndoe"
# [[params.social]]
#     name = "RSS"
#     icon = "fa fa-rss"
#     weight = 6
#     url = "https://myhugosite.com/index.xml"
#     rel = "alternate"
#     type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Services"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.de-de]
        languagename = "Deutsch"
        title = "Vicente Guerrero"

        [languages.de-de.params]
            author = "Vicente Guerrero"
            info = "Software Entwickler"
            description = "Personal Website von Vicente Guerrero"
            keywords = "blog,entwickler,software"
            footercontent = "Lass uns zusammen arbeiten."

        [languages.de-de.menu]

            [[languages.de-de.menu.main]]
            name = "Ãœber"
            weight = 1
            url = "about/"

            [[languages.de-de.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.de-de.menu.main]]
            name = "Dienste"
            weight = 3
            url = "projects/"

            [[languages.de-de.menu.main]]
            name = "Kontakt"
            weight = 5
            url = "contact/"